### ISSUE TITLE
Module 3 - Make it possible to view processed pictures in case the S3 bucket hosting them is not public 

### ISSUE THREAD

**Issue by o7g8** [aws-samples/aws-serverless-workshop-innovator-island#48]
Currently the front-end JS gives following errors in the console:
GET https://theme-park-backend-finalbucket-vi3m5d3fag5l.s3.amazonaws.com/5f3de0fc-687c-49a5-aaa4-fcae894ad1e7.jpg 403 (Forbidden)
5f3de0fc-687c-49a5-aaa4-fcae894ad1e7.jpg:1 GET https://theme-park-backend-finalbucket-vi3m5d3fag5l.s3.amazonaws.com/5f3de0fc-687c-49a5-aaa4-fcae894ad1e7.jpg 403 (Forbidden)

Maybe pre-signed URLs will address the issue.

**Comment by jbesw** [comment]
The purpose of this tutorial is to show developers how to use public objects in S3 buckets for distributing media.

If you receive this error, it is usually because you have a restriction in your AWS account to use public S3 objects. Please use a personal account without restriction, or use an Event Engine account provided at an AWS event.
