### ISSUE TITLE
Spice Capacity

### ISSUE THREAD

**Issue by msailes** [aws-samples/aws-serverless-workshop-innovator-island#54]
Yesterday I helped run this workshop of a customer and we hit a problem with the Amazon QuickSight module. 

We hit a 'Not enough SPICE capacity' error (screenshot attached). 

As a work around we deleted data from the S3 bucket. Can the workshop be modified so this doesn't happen?

Thanks,

<img width="574" alt="Screenshot 2021-01-27 at 14 25 37" src="https://user-images.githubusercontent.com/45629314/106110136-3e8b8980-6142-11eb-8be3-a354e2746eb8.png">

**Comment by jbesw** [comment]
In a new AWS account or one provided with Event Engine, there will be enough SPICE capacity. However, if the customer uses an existing account where they have used QuickSight before, it's possible that they have already consumed some of the capacity. 

This is a tricky problem since I wanted the simulation to generate a significant amount of data to show how the features work. But maybe the answer is to have a Help/FAQ section on this page that describes how to fix this problem if it occurs. What do you think?

**Comment by msailes** [comment]
This was with an Event Engine account.

**Comment by jbesw** [comment]
That's very odd. I'll dig into this further.

**Comment by jbesw** [comment]
I've modified the simulator to reduce the amount of data produced by ~20%. This should resolve edge conditions where the amount of data produced is slightly higher than the default amount of SPICE storage available.
